app/app/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path, re_path, include
from cms.sitemaps import CMSSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.i18n import JavaScriptCatalog
from django.conf import settings
from django.conf.urls.static import static

js_info_dict = {
    'packages': ('recurrence', ),
}


urlpatterns = [
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}),
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), js_info_dict),
    # re_path(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    path('search/', include('haystack.urls')),
    path('core/', include('core.system_urls')),
    path("prometheus/", include("django_prometheus.urls")),
    path('admin/', admin.site.urls),
    # path('', include('structure.system_urls')),
    path('', include('cms.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

app/structure/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', OrganizationListView.as_view(), name='index'),
    # path('orgs/<int:pk>', OrganizationDetailView.as_view(), name='org-detail'),
] 

app/structure/models.py
from django.db import models
from djangocms_text_ckeditor.fields import HTMLField
from filer.fields.image import FilerImageField
from filer.fields.file import File
from core.models import OrderedModel
from easy_thumbnails.files import get_thumbnailer
from django.urls import reverse, NoReverseMatch
from phonenumber_field.modelfields import PhoneNumberField
from cms.models.fields import PlaceholderField, PageField
from cms.models.pluginmodel import CMSPlugin
from django.dispatch import receiver
import os


class StructureBase(OrderedModel):

    
    class Meta:
        abstract = True


class CategoryOrganization(StructureBase):
    name = models.CharField(verbose_name="Полное название", max_length=128)

    class Meta:
        verbose_name = "вид организаций"
        verbose_name_plural = "виды организаций"

    def __str__(self):
        return self.name
    

    def get_absolute_url(self):
        return "{}?category={}".format(reverse("structure:index"), self.pk)
    

class Organization(StructureBase):
    category = models.ForeignKey(CategoryOrganization, verbose_name="Вид организации (не обязательно)",
                                 on_delete=models.SET_NULL, blank=True, null=True)
    parent = models.ForeignKey('self', verbose_name="Родительская организация",
                            on_delete=models.SET_NULL,
                            blank=True, null=True,)
    # уровень вложенности записи
    level = models.PositiveSmallIntegerField(default=1, blank=True, null=True)
    # номер в общем списке, учитывая древовидную структуру
    list_order = models.PositiveSmallIntegerField(default=0, blank=True, null=True)
    name = models.CharField(verbose_name="Полное название", max_length=256)
    short_name = models.CharField(verbose_name="Краткое название", max_length=128, )
    address = models.CharField(verbose_name="Адрес", max_length=256,
                             blank=True, null=True)
    phone = PhoneNumberField(verbose_name="Телефон приемной")
    fax = models.CharField(verbose_name="Факс приемной", max_length=32,
                             blank=True, null=True)
    email = models.EmailField(verbose_name='Электронная почта',
                              blank=True, null=True)
    site = models.URLField(verbose_name="Сайт", blank=True, null=True)
    shedule = models.CharField(verbose_name="График работы", max_length=256,
                              blank=True, null=True)
    phone = models.CharField(verbose_name="Телефон приемной", max_length=32,
                             blank=True, null=True)
    logo = FilerImageField(verbose_name="Логотип", 
                           on_delete=models.CASCADE, 
                           blank=True, null=True)
    # content = PlaceholderField('content')
    page = PageField(verbose_name="Ссылка на страницу", blank=True, null=True)

    # PRIEM?
    # DOCUMENT (основной документ, положение, устав)?
    # ВИДЫ ДЕЯТЕЛЬНОСТИ? (САМБО ДЗЮДО И т.д.)?

    def __str__(self):
        return self.short_name
    
    def leveled_name(self):
        if self.level > 1:
            return '|---' * (self.level - 1) + self.name
        else:
            return self.name

    leveled_name.short_description = "Название"

    def childs(self):
        return Organization.objects.filter(parent=self)

    def get_otdels(self):
        return self.otdel_set.all()
    
    def apparat(self):
        return self.sotrudnik_set.filter(apparat=True)
    
    def update_list_order(self, parent_id=None, start_order=1):
        '''обновляет порядок всех элементов при выводе списком'''
        # получаем соседние объекты
        menus = list(Organization.objects.filter(parent_id=parent_id).order_by('order'))
        if len(menus) == 0:
            return start_order

        new_order = start_order
        for obj in menus:
            obj.list_order = new_order
            obj.save(update_fields=['list_order'], lock_recursion=True)
            new_order = obj.update_list_order(parent_id=obj.id, start_order= new_order + 1)
        return new_order

    def save(self, lock_recursion=False, *args, **kwargs):
        if self.parent_id:
            self.level = Organization.objects.get(id=self.parent_id).level + 1
        else:
            self.level = 1

        super().save(*args, **kwargs)

        # save method для OrderedModel
        if not lock_recursion:
            self.update_order(
                list_of_objects = list(
                    Organization.objects.filter(parent=self.parent).exclude(id=self.id)
                    )
            )
            # обновляем номера в общем списке
            self.update_list_order()

    def logo_thumb_src(self):
        logo = self.logo
        if not logo:
            return ""

        thumbnail_options = {
            'size': (155, 200),
            'crop': False,
            'upscale': True,
            'subject_location': logo.subject_location,
        }
        thumbnailer = get_thumbnailer(logo)
        return thumbnailer.get_thumbnail(thumbnail_options).url

    def get_absolute_url(self):
        return self.page.get_absolute_url() if self.page else None
        # return reverse("org-detail", kwargs={"pk": self.pk})
    

    class Meta:
        ordering = ['list_order' ]
        verbose_name = "организация"
        verbose_name_plural = "организации"


class Activity(StructureBase):
    name = models.CharField("Название")
    logo = FilerImageField(verbose_name="Лого", 
                           on_delete=models.CASCADE)

    class Meta:
        verbose_name = "вид деятельности"
        verbose_name_plural = "виды деятельности"

    def __str__(self):
        return self.name

    def thumb_src(self):
        image = self.logo
        if not image:
            return None

        thumbnail_options = {
            'size': (193, 115),
            'crop': True,
            'upscale': True,
            'subject_location': image.subject_location,
        }
        thumbnailer = get_thumbnailer(image)
        return thumbnailer.get_thumbnail(thumbnail_options).url
    
    def get_absolute_url(self):
        try:
            return "{}?activity={}".format(reverse("department:index"), self.pk)
        except NoReverseMatch:
            return "#"

class Department(StructureBase):

    organization = models.ForeignKey(Organization, verbose_name="Организация", on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, verbose_name="Вид деятельности", on_delete=models.CASCADE)
    name = models.CharField("Название")
    schedule  = models.CharField("Режим работы", max_length=256, blank=True, null=True)
    address_same = models.BooleanField("Адрес совпадает с адресом организации", default=True)
    address = models.CharField("Адрес", max_length=512, blank=True, null=True,
                               help_text="Заполняется если адрес секции не совпадает с адресом организации")
    phone = PhoneNumberField(verbose_name="Телефон", blank=True, null=True)
    description = HTMLField("Описание")

    def __str__(self):
        return self.name
    
    def get_address(self):
        return self.organization.address if self.address_same else self.address

    def get_photos(self):
        return self.photodepartment_set.all()

    class Meta:
        verbose_name = "секция"
        verbose_name_plural = "секции"

class PhotoDepartment(StructureBase):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    photo = FilerImageField(verbose_name="Фото", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "фото"
        verbose_name_plural = "фото"

    def thumb_src(self):
        image = self.photo
        if not image:
            return None

        thumbnail_options = {
            'size': (150, 130),
            'crop': True,
            'upscale': True,
            'subject_location': image.subject_location,
        }
        thumbnailer = get_thumbnailer(image)
        return thumbnailer.get_thumbnail(thumbnail_options).url



@receiver(models.signals.post_delete, sender=PhotoDepartment)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Удаляет файл при удалении объекта
    """
    if instance.photo:
        if os.path.isfile(instance.photo.path):
            # delete file from file system
            os.remove(instance.photo.path)
            # delete Filer File object
            File.objects.filter(id=instance.photo_id).delete()


class Otdel(StructureBase):
    organization = models.ForeignKey(Organization, verbose_name="Организация",
                                     on_delete=models.CASCADE)
    name = models.CharField(verbose_name="Название", max_length=256)
    page = PageField(verbose_name="Ссылка на страницу", blank=True, null=True,
                          help_text="Не обязательно")
    # PHONEs?


    def __str__(self):
        return self.name

    def save(self, lock_recursion=False, *args, **kwargs):
        # save method для OrderedModel
        super().save(*args, **kwargs)

        if not lock_recursion:
            self.update_order(
                list_of_objects = list(
                    Otdel.objects.filter(organization=self.organization).exclude(id=self.id)
                    )
            )

    def get_employees(self):
        return self.sotrudnik_set.all()

    def phones(self):
        return self.phone_set.all()

    def get_absolute_url(self):
        return self.page.get_absolute_url() if self.page else None

    class Meta:
        ordering = ['organization', 'order' ]
        verbose_name = "отдел"
        verbose_name_plural = "отделы"


class Sotrudnik(StructureBase):
    organization = models.ForeignKey(Organization, verbose_name="Организация",
                                     on_delete=models.CASCADE)
    otdel = models.ForeignKey(Otdel, verbose_name="Отдел",
                            on_delete=models.SET_NULL,
                            blank=True, null=True,

app/structure/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.views.generic import View
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, JsonResponse, Http404
from .models import Organization, Otdel, CategoryOrganization, Department, Activity
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from django.http import Http404
from django.shortcuts import get_object_or_404
from django_filters.views import FilterView
from .filtersets import DepartmentFilterSet


# ACTION_LIST = ("get-otdels", )
# RESULTS = {
#     0 : "error",
#     1 : "success",
# }
# class AdminView(View):

#     def dispatch(self, request, *args, **kwargs):

#         if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
#             return self.ajax_post(request, *args, **kwargs)

#         return super().dispatch(request, *args, **kwargs)
    

#     def ajax_post(self, request, *args, **kwargs):

#         if not request.user.is_authenticated:
#             raise PermissionDenied

#         action = request.POST.get("action")
#         org_id = request.POST.get("org_id")

#         if action not in ACTION_LIST:
#             raise Http404

#         try:
#             org = Organization.objects.get(pk=org_id)
#         except Organization.DoesNotExist:
#             raise Http404
        
#         if org and (action == 'get-otdels'):
#             # try:
#             return self.get_otdels(request, org)
#             # except PermissionDenied:
#                 # return JsonResponse({"result": RESULTS[0], "message": "Нет прав доступа для этой операции"})

#         raise Http404

#     # @method_decorator(permission_required("structure.change_otdel", raise_exception=True))
#     def get_otdels(self, request, org:Organization):
#         '''Switching publish state of Post'''

#         return JsonResponse({"result": RESULTS[1], 
#                              "message": "Данные получены", 
#                              "data": org.get_otdels()})
        # if post.published:
        #     post.published = False
        #     post.save()
        #     return JsonResponse({"result": RESULTS[1], "message": "Снято с публикации"})
        # else:
        #     # if post has child plugins
        #     if CMSPlugin.objects.filter(placeholder_id=post.content_id).count() > 0:
        #         post.published = True
        #         post.save()
        #         return JsonResponse({"result": RESULTS[1], "message": "Опубликовано"})
        #     else: # no child plugins
        #         message = "Новость пуста и поэтому не может быть опубликована. \n Добавьте плагинов на страницу."
        #         return JsonResponse({"result": RESULTS[0], "message": message})


class GetOtdelsView(View):
    """
    Возвращает список отделов в ответ на ajax запрос
    Используется в форме SotrudnikForm
    Обрабатывается в js/sotrudnik_form.js

    https://simpleisbetterthancomplex.com/tutorial/2018/01/29/how-to-implement-dependent-or-chained-dropdown-list-with-django.html
    """
    def get(self,request, *args, **kwargs):

        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            org_id = request.GET.get("org_id", None)
            if org_id and org_id.isdigit():
                org = get_object_or_404(Organization, id=org_id)
                otdels = Otdel.objects.filter(organization=org).values('id', 'name')
                return JsonResponse({'data': list(otdels)})

        raise Http404
    
class OrganizationListView(ListView):
    template_name = "structure/structure.html"
    # model = Organization
    # queryset = Organization.objects.filter(level=1)

    def get_queryset(self):
        cat = self.request.GET.get("category", None)
        if cat and cat.isdigit():
            qs = Organization.objects.filter(category=cat)
        else:
            # передаем только элементы верхнего уровня
            # остальные подтягиваются рекурсивно в шаблоне
            qs = Organization.objects.filter(level=1)

        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        cat = self.request.GET.get("category", None)
        if cat and cat.isdigit():
            cat = get_object_or_404(CategoryOrganization, pk=cat)
            context['page_title'] = cat.name
        return context
    
# class OrganizationDetailView(DetailView):
#     template_name = "structure/organization_detail.html"
#     model = Organization

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['page_title'] = context['object'].name
#         return context


class DepartmentFilterView(FilterView):
    template_name = "structure/department.html"
    filterset_class = DepartmentFilterSet
    model = Department
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        activity_id = self.request.GET.get("activity", None)
        if activity_id and activity_id.isdigit():
            activity = get_object_or_404(Activity, pk=activity_id)
            context['page_title'] = activity.name
        return context

app/structure/templates/structure/plugins/activity_plugin.html
{% load cms_tags sekizai_tags easy_thumbnails_tags static %}

{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'core/css/content-box.css' %}">{% endaddtoblock %}
{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'core/css/image-box.css' %}">{% endaddtoblock %} 
{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'structure/css/structure.css' %}">{% endaddtoblock %}

<div class="activities list-items">
  <div class="grid-list gallery">
    <div class="grid-box row">
    {% for object in object_list %}
        <div class="grid-item col-md-3">
                
          {% if instance.layout == "image-blocks" %}
            <div class="img-box adv-circle circle adv-circle-center white">
                <img src="{{ object.thumb_src}}" alt="" />
                <div class="caption">
                    {% comment %} <h2>{{ object.name }}</h2> {% endcomment %}
                </div>
            </div>
          {% elif instance.layout == "blocks" %}
            <a href="{{ object.get_absolute_url }}" class="activity-button btn btn-lg btn-border">{{ object.name}}</a>
          {% endif %}

        </div>
        {% cycle '' '' '' '<div class="clear"></div>' %}
    {% endfor %}
    </div>
  </div>
</div>

app/structure/templates/structure/plugins/attributes_plugin.html
{% load sekizai_tags easy_thumbnails_tags static %}

{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'structure/css/structure.css' %}">{% endaddtoblock %}

<ul class="list-texts list-texts-justified text-left">
  {% if object.phone %}
  <li><b>Телефон приемной: </b><i class="fa fa-phone"></i> {{ object.phone }}</li>
  {% endif %}
  {% if object.email %}
  <li><b>Электронная почта: </b><i class="fa fa-envelope-open-o"></i> {{ object.email }}</li>
  {% endif %}
  {% if object.address %}
  <li><b>Адрес: </b><i class="fa fa-map-marker"></i> {{ object.address }}</li>
  {% endif %}
  {% if object.site %}
  <li><b>Сайт: </b><a href="{{ object.site }}" target="_blank">{{ object.site }} <i class="fa fa-external-link text-s"></i></a></li>
  {% endif %}
  {% if object.shedule %}
  <li><b>График работы: </b><i class="fa fa-calendar"></i> {{ object.shedule }}</li>
  {% endif %}
</ul>

app/structure/templates/structure/plugins/department_plugin.html
{% load cms_tags sekizai_tags easy_thumbnails_tags static %}

{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'core/css/content-box.css' %}">{% endaddtoblock %}
{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'core/css/image-box.css' %}">{% endaddtoblock %} 
{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'structure/css/structure.css' %}">{% endaddtoblock %}
{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'core/scripts/magnific-popup.css' %}">{% endaddtoblock %}
{% addtoblock "js" %}<script  src="{% static 'core/scripts/jquery.magnific-popup.min.js' %}"></script>{% endaddtoblock %}
  

{% include 'structure/includes/department_list.html' %}

app/structure/templates/structure/plugins/logo_plugin.html
{% load sekizai_tags easy_thumbnails_tags static %}

{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'structure/css/structure.css' %}">{% endaddtoblock %}
{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'core/css/image-box.css' %}">{% endaddtoblock %} 

{% if object.logo %}
<div class="img-box">
  <img src="{{ object.logo_thumb_src }}" alt="">
</div>
{% endif %}

app/structure/templates/structure/plugins/otdel_organization_plugin.html
{% load cms_tags sekizai_tags easy_thumbnails_tags static %}


{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'core/css/content-box.css' %}">{% endaddtoblock %}
{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'core/css/image-box.css' %}">{% endaddtoblock %} 
{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'structure/css/structure.css' %}">{% endaddtoblock %}
{% addtoblock "js" %}<script  src="{% static 'core/scripts/jquery.tab-accordion.js' %}"></script>{% endaddtoblock %}

<div class="otdel-list list-group accordion-list" data-type="visible" data-time="200">
  {% for object in object_list %}
  <div class="list-group-item">
    {% comment %} {% render_model_block object %} {% endcomment %}
    <a href="#" class="">
      <div class="row">
        <div class="col-xs-8">
          {{ object.name }}
        </div>
        <div class="col-xs-4">
          <div class="text-right">
            {% for phone in object.phones %}
              <div><span><i class="fa fa-phone"></i> {{ phone.number }}</span></div>
            {% endfor %}
          </div>
        </div>
      </div>
    </a>
    {% comment %} {% endrender_model_block %} {% endcomment %}
    <div class="panel" style="display: none;">
      <div class="inner text-center">

          {% include 'structure/plugins/sotrudnik_organization_plugin.html' with object_list=object.get_employees layout="rows" instance=None %}

          {% if SHOW_DETAIL_LINK and object.page %}
            <a href="{{ object.get_absolute_url }}" class="btn btn-lg btn-border w-100">Подробнее об отделе</a>
            <hr class="space s">
          {% endif %}

      </div>
    </div>
  </div>
  {% empty %}
  Сведений по отделам пока нет.
  {% endfor %}
</div>

app/structure/templates/structure/plugins/sotrudnik_organization_plugin.html
{% load cms_tags sekizai_tags easy_thumbnails_tags static %}

{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'core/css/content-box.css' %}">{% endaddtoblock %}
{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'core/css/image-box.css' %}">{% endaddtoblock %} 
{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'structure/css/structure.css' %}">{% endaddtoblock %}

<div class="sotrudnik-list">
{% if layout == "rows" %}

  <div class="row">
    {% for object in object_list %}
      <div class="col-md-12">
        {% render_model_block object %}
        <div class="apparat-item">
            <div class="advs-box advs-box advs-box-side-icon boxed-inverse">
                <div class="row vertical-row">
                    <div class="col-xs-3 col-lg-2 text-center">
                        <div class="photo img-box">
                            {% if object.photo %}
                            <img src="{{ object.photo_thumb_src }}" alt="">
                            {% else %}
                            <i class="fa fa-user-o"></i>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-xs-9 col-lg-10">
                        {% comment %} <h3><a href="{% url 'structure:org-detail' object.id %}">{{ object.name }}</a></h3> {% endcomment %}
                        <h3>
                          {% if SHOW_DETAIL_LINK and object.page %}
                            <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
                          {% else %}
                            {{ object.name }}
                          {% endif %}
                        </h3>
                        <p>{{ object.position }}</p>
                        <hr class="space xs">
                        {% for phone in object.phones %}
                          <div><span><i class="fa fa-phone"></i> {{ phone.number }}</span></div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endrender_model_block %}
      </div>
    {% empty %}
    Сведений по сотрудникам пока нет.
    {% endfor %}
  </div>

{% elif layout == "blocks" %}
  <div class="grid-list">
    <div class="grid-box row">
      {% for object in object_list %}
        {% render_model_block object %}
        <div class="grid-item col-md-3">
          <div class="advs-box advs-box-top-icon boxed-inverse">
              {% if object.photo %}
              <img src="{{ object.photo_thumb_src }}" height="100" alt="">
              {% else %}
              <i class="fa fa-user-o text-xl"></i>
              {% endif %}
            <div class="advs-box-content">
                <h3>
                  {% if SHOW_DETAIL_LINK and object.page %}
                    <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
                  {% else %}
                    {{ object.name }}
                  {% endif %}
                </h3>
                <p>{{ object.position }}</p>
                <hr>
                {% for phone in object.phones %}
                  <div><span><i class="fa fa-phone"></i> {{ phone.number }}</span></div>
                {% endfor %}
            </div>
          </div>
        </div>
        {% endrender_model_block %}
        {% cycle '' '' '' '<div class="clear"></div>' %}
      {% empty %}
      Сведений по сотрудникам пока нет.
      {% endfor %}
    </div>
  </div>

{% endif %}
  <div class="clear"></div>
</div>